//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarekMachlinskiLab8Zad1.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class MarekMachlinskiPlayer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MarekMachlinskiPlayer()
        {
            this.MarekMachlinskiSavedGames = new HashSet<MarekMachlinskiSavedGame>();
        }
    
        public string Login { get; set; }
        public string Password { get; set; }
        public System.DateTime CreationDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MarekMachlinskiSavedGame> MarekMachlinskiSavedGames { get; set; }
    }
}
