//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarekMachlinskiLab8Zad1.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class MarekMachlinskiSavedGame
    {
        public int ID { get; set; }
        public string PlayerLogin { get; set; }
        public System.DateTime LastSaveDate { get; set; }
        public int PointsLeft { get; set; }
        public int AssemblerLevel { get; set; }
        public int VisualBasicLevel { get; set; }
        public int CLevel { get; set; }
        public int CppLevel { get; set; }
        public int CSharpLevel { get; set; }
        public int FSharpLevel { get; set; }
        public int JavaLevel { get; set; }
        public int JavaScriptLevel { get; set; }
        public int PHPLevel { get; set; }
        public int PythonLevel { get; set; }
    
        public virtual MarekMachlinskiPlayer MarekMachlinskiPlayer { get; set; }
    }
}
