USE master;
GO

IF DB_ID (N'CalcCL') IS NOT NULL
BEGIN
	ALTER DATABASE CalcCL 
	SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
	DROP DATABASE CalcCL;
END;
CREATE DATABASE CalcCL;
GO
USE CalcCL;
GO

CREATE TABLE Users(
	ID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	Login NVARCHAR(32) NOT NULL
);

CREATE TABLE Subjects(
	ID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	Name NVARCHAR(63) NOT NULL
);

CREATE TABLE Scores(
	ID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	Value DECIMAL(2, 1) NOT NULL
);

CREATE TABLE Marks(
	UserID INT NOT NULL,
	SubjectID INT NOT NULL,
	ScoreID INT NOT NULL,
	Weight TINYINT NOT NULL CHECK(Weight >= 0) DEFAULT 0,
	FOREIGN KEY(UserID) REFERENCES Users(ID),
	FOREIGN KEY(SubjectID) REFERENCES Subjects(ID),
	FOREIGN KEY(ScoreID) REFERENCES Scores(ID)
);
GO

INSERT INTO Scores VALUES
	(2.0),
	(3.0),
	(3.5),
	(4.0),
	(4.5),
	(5.0),
	(5.5);
GO